"""empty message

Revision ID: 84203a5d5ffd
Revises: 
Create Date: 2020-08-05 22:43:43.186166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84203a5d5ffd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    """op.create_table('Subscribe', 
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('sub', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['Client.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('sqlite_sequence')
    op.drop_table('subscribe')
    op.alter_column('Client', 'address',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('Client', 'date_of_birth',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('Client', 'email',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('Client', 'first_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('Client', 'gender',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('Client', 'last_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('Client', 'phone_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'Client', ['id'])
    op.create_unique_constraint(None, 'Client', ['email'])
    op.create_unique_constraint(None, 'Client', ['phone_number'])"""
    op.add_column('User', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'confirmed_at')
    """op.drop_constraint(None, 'Client', type_='unique')
    op.drop_constraint(None, 'Client', type_='unique')
    op.drop_constraint(None, 'Client', type_='unique')
    op.alter_column('Client', 'phone_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Client', 'last_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('Client', 'gender',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('Client', 'first_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('Client', 'email',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('Client', 'date_of_birth',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('Client', 'address',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_table('subscribe',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('client_id', sa.INTEGER(), nullable=True),
    sa.Column('sub', sa.INTEGER(), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['Client.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    op.drop_table('Subscribe')"""
    # ### end Alembic commands ###
